Attribute VB_Name = "modTOOLTIPtexte"
Option Explicit

'Modulbeschreibung:
'Ein- bzw. Ausblenden der Tooltips
'---------------------------------

Public Sub TooltipsON()
    Select Case g_strSprache
        Case "DE"
            With frmGUI
                'Allgemeine Elemente
                .imgFlaggeDE.ControlTipText = ""
                .imgFlaggeEN.ControlTipText = "Switch to English"
                .btnReset.ControlTipText = "Aktuelle Selektion zurücksetzen und zugehörige Hervorhebungen und Linien auf dem Tabellenblatt löschen"
                .btnBereicheAnzeigen.ControlTipText = "Anzeigen der aktuell in das Tool eingelesenen Bereiche auf dem Tabellenblatt"
                
                'Page "Vergleichen"
                .lblAreaVergleich1.ControlTipText = "Aktuell in das Tool eingelesener Bereich (Adresse auf dem Tabellenblatt)"
                .lblAreaVergleich2.ControlTipText = "Aktuell in das Tool eingelesener Bereich (Adresse auf dem Tabellenblatt)"
                .btnArea1.ControlTipText = "Einlesen des ersten Bereichs in das Tool"
                .btnArea2.ControlTipText = "Einlesen des zweiten Bereichs in das Tool"
                .btnAreaBeide.ControlTipText = "Einlesen beider Bereiche in das Tool mit einem Klick"
                .btnCurrentRegion.ControlTipText = "Selektieren der angrenzenden Zellen auf dem Tabellenblatt zum schnellen Einlesen der Bereiche"
                .btnSchnellCheck.ControlTipText = "Prüfung auf Zeichen, die den Vergleich beeinflussen können"
                .btnStart.ControlTipText = "Starten der Suche nach Wertpaaren unter Beachtung der nebenstehenden Optionen"
                .frameVergleichsoptionen.ControlTipText = "Hier kann festgelegt werden, nach welchen Kriterien die Suche abläuft"
                .checkboxGrossKleinBuchstaben.ControlTipText = "Hier kann festgelegt werden, nach welchen Kriterien die Suche abläuft"
                .checkboxLeerzeichen.ControlTipText = "Hier kann festgelegt werden, nach welchen Kriterien die Suche abläuft"
                .frameAnzeige.ControlTipText = "Die Darstellung auf dem Tabellenblatt kann auch nachträglich in der Registerkarte 'Visualisierung' vorgenommen werden"
                .checkboxLinien.ControlTipText = "Die Darstellung auf dem Tabellenblatt kann auch nachträglich in der Registerkarte 'Visualisierung' vorgenommen werden"
                .checkboxHervorhebenEinzeln.ControlTipText = "Die Darstellung auf dem Tabellenblatt kann auch nachträglich in der Registerkarte 'Visualisierung' vorgenommen werden"
                .checkboxHervorhebenPaare.ControlTipText = "Die Darstellung auf dem Tabellenblatt kann auch nachträglich in der Registerkarte 'Visualisierung' vorgenommen werden"
                
                'Page "Hervorbehen"
                .btnHervorhebenEinzeln.ControlTipText = "Werte, die keinen Partner im anderen Bereich haben, farbig hervorheben"
                .btnHervorhebenPaare.ControlTipText = "Werte, die in beiden Bereichen vorkommen, farbig hervorheben"
                .btnHervorhebungLoeschen.ControlTipText = "Alle farbigen Hervorhebungen in den selektierten Bereichen löschen"
                .btnLinienZeichnen.ControlTipText = "Linien zwischen den Wertpaaren zeichnen"
                .btnLinienLoeschenAktuelle.ControlTipText = "Die Linien des aktuellen Vergleichs auf dem Tabellenblatt löschen"
                .btnLinienLoeschenAlle.ControlTipText = "Alle Linien auf dem Tabellenblatt, die von diesem Tool gezeichnet wurden, löschen"
                
                'Page "Ausgeben"
                .frameAusgeben1.ControlTipText = "Die unten ausgewählten Werte können in einem neuen Tabellenblatt oder ab der aktuellen Cursorposition ausgegeben werden"
                .optAusgNeu.ControlTipText = "Die unten ausgewählten Werte können in einem neuem Tabellenblatt oder ab der aktuellen Cursorposition ausgegeben werden"
                .optAusgCursor.ControlTipText = "Die unten ausgewählten Werte können in neuem Tabellenblatt oder ab der aktuellen Cursorposition ausgegeben werden"
                .frameAusgeben2.ControlTipText = "Ausgeben der Einzelwerte an der unter 'Ausgabeort' angegebenen Position"
                .optAusg1Beide.ControlTipText = "Ausgeben der Einzelwerte an der unter 'Ausgabeort' angegebenen Position"
                .optAusg1Nur1.ControlTipText = "Ausgeben der Einzelwerte an der unter 'Ausgabeort' angegebenen Position"
                .optAusg1Nur2.ControlTipText = "Ausgeben der Einzelwerte an der unter 'Ausgabeort' angegebenen Position"
                .btnAusgabe1.ControlTipText = "Ausgeben der Einzelwerte an der unter 'Ausgabeort' angegebenen Position"
                .frameAusgeben3.ControlTipText = "Ausgeben der Wertpaare an der unter 'Ausgabeort' angegebenen Position"
                .optAusg2Beide.ControlTipText = "Ausgeben der Wertpaare an der unter 'Ausgabeort' angegebenen Position"
                .optAusg2Nur1.ControlTipText = "Ausgeben der Wertpaare an der unter 'Ausgabeort' angegebenen Position"
                .optAusg2Nur2.ControlTipText = "Ausgeben der Wertpaare an der unter 'Ausgabeort' angegebenen Position"
                .btnAusgabe2.ControlTipText = "Ausgeben der Wertpaare an der unter 'Ausgabeort' angegebenen Position"
                
                 'Page "Bereinigen"
                .lblCheckBereichText1.ControlTipText = "Zellen, die geprüft bzw. bereinigt werden"
                .lblCheckBereichText2.ControlTipText = "Zellen, die geprüft bzw. bereinigt werden"
                .lblCheckArea1.ControlTipText = "Zellen, die geprüft bzw. bereinigt werden"
                .lblCheckArea2.ControlTipText = "Zellen, die geprüft bzw. bereinigt werden"
                .btnCheckAll.ControlTipText = "Gesamt-Check auf unnötige Leerzeichen, geschützte Leerzeichen (Unicode-Zeichen 160) und Steuerzeichen (7-Bit-ASCII-Zeichen 0-31 und Unicode-Zeichen 127, 129, 141, 143, 144 und 157)"
                .btnCheckLeer.ControlTipText = "Check auf unnötige Leerzeichen (am Anfang oder Ende einer Zelle und mehrfach aufeinanderfolgende Leerzeichen)"
                .btnCheckSteuer.ControlTipText = "Check auf Steuerzeichen (7-Bit-ASCII-Zeichen 0-31 und Unicode-Zeichen 127, 129, 141, 143, 144 und 157)"
                .btnCheckGesch.ControlTipText = "Check auf geschützte Leerzeichen (Unicode-Zeichen 160)"
                .btnFixAll.ControlTipText = "Unwiderrufliches Entfernen von unnötigen Leerzeichen, geschützten Leerzeichen (Unicode-Zeichen 160) und Steuerzeichen (7-Bit-ASCII-Zeichen 0-31 und Unicode-Zeichen 127, 129, 141, 143, 144 und 157)"
                .btnFixLeer.ControlTipText = "Unwiderrufliches Entfernen von unnötigen Leerzeichen (am Anfang oder Ende einer Zelle und mehrfach aufeinanderfolgende Leerzeichen)"
                .btnFixSteuer.ControlTipText = "Unwiderrufliches Entfernen von Steuerzeichen (7-Bit-ASCII-Zeichen 0-31 und Unicode-Zeichen 127, 129, 141, 143, 144 und 157)"
                .btnFixGesch.ControlTipText = "Unwiderrufliches Entfernen von geschützten Leerzeichen (Unicode-Zeichen 160)"
                
                'Page "Info"
                .btnAnleitung.ControlTipText = "Ausführliche Anleitung zu allen Funktionen des Tools"
                .btnFeatures.ControlTipText = "Features des Tools und Versionshistorie"
                .btnSourceCode.ControlTipText = "Aufruf der GitHub-Webseite mit dem Quellcode des Tools im Standardbrowser"
                .btnDisclaimer.ControlTipText = "Nutzungsbedingungen des Tools"
                .btnFeedback.ControlTipText = "Senden einer E-Mail über das Standard-Mailprogramm (alternativ kann die untenstehende E-Mail-Adresse verwendet werden)"
                
                'Page "Spenden"
                .imgPrinz.ControlTipText = "Aufrufen der Website der Stiftung 'Große Hilfe für kleine Helden' im Standardbrowser"
                .imgQRcode.ControlTipText = "QR-Code scannen zum Aufruf des Online-Spendenformulars"
            End With
            
        Case "EN"
            With frmGUI
                'Allgemeine Elemente
                .imgFlaggeDE.ControlTipText = "Auf Deutsch anzeigen"
                .imgFlaggeEN.ControlTipText = ""
                .btnReset.ControlTipText = "Reset the current selection and remove all highlightings and corresponding connection lines on the worksheet"
                .btnBereicheAnzeigen.ControlTipText = "Show currently selected areas on the worksheet"
                
                'Page "Vergleichen"
                .lblAreaVergleich1.ControlTipText = "Currently selected area (worksheet address)"
                .lblAreaVergleich2.ControlTipText = "Currently selected area (worksheet address)"
                .btnArea1.ControlTipText = "Klick to read in the first area"
                .btnArea2.ControlTipText = "Klick to read in the second area"
                .btnAreaBeide.ControlTipText = "Klick to read in both areas"
                .btnCurrentRegion.ControlTipText = "Select the current worksheet region"
                .btnSchnellCheck.ControlTipText = "Check for characters which can impact the comparision"
                .btnStart.ControlTipText = "Start searching for pairs according to the criteria in the options section"
                .frameVergleichsoptionen.ControlTipText = "Search criteria"
                .checkboxGrossKleinBuchstaben.ControlTipText = "Search criteria"
                .checkboxLeerzeichen.ControlTipText = "Search criteria"
                .frameAnzeige.ControlTipText = "All actions can also be executed in the 'Visualisation' tab after the comparison"
                .checkboxLinien.ControlTipText = "All actions can also be executed in the 'Visualisation' tab after the comparison"
                .checkboxHervorhebenEinzeln.ControlTipText = "All actions can also be executed in the 'Visualisation' tab after the comparison"
                .checkboxHervorhebenPaare.ControlTipText = "All actions can also be executed in the 'Visualisation' tab after the comparison"
                
                'Page "Hervorbehen"
                .btnHervorhebenEinzeln.ControlTipText = "Highlight all data records which do not have a corresponding record in the other area"
                .btnHervorhebenPaare.ControlTipText = "Highlight all pairs of data records in each area"
                .btnHervorhebungLoeschen.ControlTipText = "Remove all highlightings in the selected areas"
                .btnLinienZeichnen.ControlTipText = "Draw connection lines between all pairs of data records"
                .btnLinienLoeschenAktuelle.ControlTipText = "Remove all connection lines on the data sheet which have been drawn in the current run"
                .btnLinienLoeschenAlle.ControlTipText = "Remove all connection lines on the data sheet which have been drawn by this tool"
                
                'Page "Ausgeben"
                .frameAusgeben1.ControlTipText = "The data records chosen below can be printed on a new worksheet or at the current cursor position"
                .optAusgNeu.ControlTipText = "The data records chosen below can be printed on a new worksheet or at the current cursor position"
                .optAusgCursor.ControlTipText = "The data records chosen below can be printed on a new worksheet or at the current cursor position"
                .frameAusgeben2.ControlTipText = "Printing the single data records at the location chosen above"
                .optAusg1Beide.ControlTipText = "Printing the single data records at the location chosen above"
                .optAusg1Nur1.ControlTipText = "Printing the single data records at the location chosen above"
                .optAusg1Nur2.ControlTipText = "Printing the single data records at the location chosen above"
                .btnAusgabe1.ControlTipText = "Printing the single data records at the location chosen above"
                .frameAusgeben3.ControlTipText = "Printing the data records pairs at the location chosen above"
                .optAusg2Beide.ControlTipText = "Printing the data records pairs at the location chosen above"
                .optAusg2Nur1.ControlTipText = "Printing the data records pairs at the location chosen above"
                .optAusg2Nur2.ControlTipText = "Printing the data records pairs at the location chosen above"
                .btnAusgabe2.ControlTipText = "Printing the data records pairs at the location chosen above"
                
                 'Page "Bereinigen"
                .lblCheckBereichText1.ControlTipText = "Cells to be checked or cleaned"
                .lblCheckBereichText2.ControlTipText = "Cells to be checked or cleaned"
                .lblCheckArea1.ControlTipText = "Cells to be checked or cleaned"
                .lblCheckArea2.ControlTipText = "Cells to be checked or cleaned"
                .btnCheckAll.ControlTipText = "Complete check for unnecessary spaces, non-breaking spaces (unicode character 160) and control characters (7-bit ASCII code characters 0-31 and unicode characters 127, 129, 141, 143, 144 and 157)"
                .btnCheckLeer.ControlTipText = "Check for unnecessary spaces (at the beginning or the end of a cell and multiple spaces within a cell)"
                .btnCheckSteuer.ControlTipText = "Check for control characters (7-bit ASCII code characters 0-31 and unicode characters 127, 129, 141, 143, 144 and 157)"
                .btnCheckGesch.ControlTipText = "Check for non-breaking spaces (unicode character 160)"
                .btnFixAll.ControlTipText = "Irreversible removal of unnecessary spaces, non-breaking spaces (unicode character 160) and control characters (7-bit ASCII code characters 0-31 and unicode characters 127, 129, 141, 143, 144 and 157)"
                .btnFixLeer.ControlTipText = "Irreversible removal of unnecessary spaces (at the beginning or the end of a cell and multiple spaces within a cell)"
                .btnFixSteuer.ControlTipText = "Irreversible removal of control characters (7-bit ASCII code characters 0-31 and unicode characters 127, 129, 141, 143, 144 and 157)"
                .btnFixGesch.ControlTipText = "Irreversible removal of non-breaking spaces (unicode character 160)"
                
                'Page "Info"
                .btnAnleitung.ControlTipText = "Detailed manual of all functions"
                .btnFeatures.ControlTipText = "Features of the tool and version history"
                .btnSourceCode.ControlTipText = "Open the GitHub web page containing the source code of the tool in your standard browser"
                .btnDisclaimer.ControlTipText = "Disclaimer and terms of use"
                .btnFeedback.ControlTipText = "Send an email using your standard email client (if not possible use the email address below)"
                
                'Page "Spenden"
                .imgPrinz.ControlTipText = "Open the web site of the foundation 'Große Hilfe für kleine Helden' in your standard browser"
                .imgQRcode.ControlTipText = "Scan this QR code for online donation"
            End With
        
        Case Else
            
    End Select
End Sub

Public Sub TooltipsOFF()
    With frmGUI
        'Allgemeine Elemente
        .imgFlaggeDE.ControlTipText = ""
        .imgFlaggeEN.ControlTipText = ""
        .btnReset.ControlTipText = ""
        .btnBereicheAnzeigen.ControlTipText = ""
        
        'Page "Vergleichen"
        .lblAreaVergleich1.ControlTipText = ""
        .lblAreaVergleich2.ControlTipText = ""
        .btnArea1.ControlTipText = ""
        .btnArea2.ControlTipText = ""
        .btnAreaBeide.ControlTipText = ""
        .btnCurrentRegion.ControlTipText = ""
        .btnSchnellCheck.ControlTipText = ""
        .btnStart.ControlTipText = ""
        .frameVergleichsoptionen.ControlTipText = ""
        .checkboxGrossKleinBuchstaben.ControlTipText = ""
        .checkboxLeerzeichen.ControlTipText = ""
        .frameAnzeige.ControlTipText = ""
        .checkboxLinien.ControlTipText = ""
        .checkboxHervorhebenEinzeln.ControlTipText = ""
        .checkboxHervorhebenPaare.ControlTipText = ""
        
        'Page "Hervorbehen"
        .btnHervorhebenEinzeln.ControlTipText = ""
        .btnHervorhebenPaare.ControlTipText = ""
        .btnHervorhebungLoeschen.ControlTipText = ""
        .btnLinienZeichnen.ControlTipText = ""
        .btnLinienLoeschenAktuelle.ControlTipText = ""
        .btnLinienLoeschenAlle.ControlTipText = ""
        
        'Page "Ausgeben"
        .frameAusgeben1.ControlTipText = ""
        .optAusgNeu.ControlTipText = ""
        .optAusgCursor.ControlTipText = ""
        .frameAusgeben2.ControlTipText = ""
        .optAusg1Beide.ControlTipText = ""
        .optAusg1Nur1.ControlTipText = ""
        .optAusg1Nur2.ControlTipText = ""
        .btnAusgabe1.ControlTipText = ""
        .frameAusgeben3.ControlTipText = ""
        .optAusg2Beide.ControlTipText = ""
        .optAusg2Nur1.ControlTipText = ""
        .optAusg2Nur2.ControlTipText = ""
        .btnAusgabe2.ControlTipText = ""
        
        'Page "Bereinigen"
        .lblCheckBereichText1.ControlTipText = ""
        .lblCheckBereichText2.ControlTipText = ""
        .btnCheckAll.ControlTipText = ""
        .btnCheckLeer.ControlTipText = ""
        .btnCheckSteuer.ControlTipText = ""
        .btnCheckGesch.ControlTipText = ""
        .btnFixAll.ControlTipText = ""
        .btnFixLeer.ControlTipText = ""
        .btnFixSteuer.ControlTipText = ""
        .btnFixGesch.ControlTipText = ""
        
        'Page "Info"
        .btnAnleitung.ControlTipText = ""
        .btnFeatures.ControlTipText = ""
        .btnSourceCode.ControlTipText = ""
        .btnDisclaimer.ControlTipText = ""
        .btnFeedback.ControlTipText = ""
        
        'Page "Spenden"
        .imgPrinz.ControlTipText = ""
        .imgQRcode.ControlTipText = ""
        
    End With
End Sub
